### ISSUE TITLE
[BUG] cudf.pandas differs from pandas for group-by with nulls

### ISSUE THREAD

**Issue by MarcoGorelli** [rapidsai/cudf#17950]
**Steps/Code to reproduce bug**
```python
%%writefile t.py

import pandas as pd
data = {"b": [4, 5, None], "a": [1, 2, 3]}
df = pd.DataFrame(data)
print(df.groupby('b', dropna=True)['a'].size())
```
```
$ python t.py
b
4.0    1
5.0    1
Name: a, dtype: int64

$ python -m cudf.pandas t.py
b
4.0    1
5.0    1
NaN    1
Name: a, dtype: int64
```

**Expected behavior**
same results

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

cudf, pandas: ('25.02.00a367', '2.2.3')

**Additional context**
another one spotted in [Narwhals](https://github.com/narwhals-dev/narwhals)

**Comment by mroeschke** [comment]
Thanks for the report. I believe this was addressed with https://github.com/rapidsai/cudf/pull/17895 which will be available in 25.04 or nightlies (once 25.02 is fully released)

**Comment by MarcoGorelli** [comment]
I used the nightly, version 25.02.00a367

**Comment by bdice** [comment]
@MarcoGorelli You can use 25.04 nightlies if you want to test the latest builds. They don't show on our [release selector yet](https://docs.rapids.ai/install/#selector) because we're still getting ready to release 25.02, but you can get them with:

```
conda create -n cudf-25.04 -c rapidsai-nightly -c conda-forge -c nvidia  \
    cudf=25.04 python=3.12 'cuda-version>=12.0,<=12.8'
```

**Comment by MarcoGorelli** [comment]
ah great, thanks! 🙏
