### ISSUE TITLE
[BUG] Unable to index cudf.DataFrame with cudf.Series ( in docker rapidsai/rapidsai:cuda9.2-runtime-ubuntu16.04)

### ISSUE THREAD

**Issue by deltadu** [rapidsai/cudf#1958]
Unable to index cudf.DataFrame with cudf.Series in rapids docker
The version is rapidsai/rapidsai:cuda9.2-runtime-ubuntu16.04

```
import numpy as np
import pandas as pd
import cudf

X = pd.DataFrame(np.ones((10, 3)), columns=list('abc'))
X = cudf.from_pandas(X)
X.iloc[cudf.Series([0, 1, 2])]
 ```
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 2900, in __getitem__
    df.index = self._df.index[arg]
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/index.py", line 486, in __getitem__
    res = self._values[index]
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/column.py", line 422, in __getitem__
    raise NotImplementedError(type(arg))
NotImplementedError: <class 'cudf.dataframe.series.Series'>
```

**Comment by shwina** [comment]
This should be fixed in cuDF 8.0 which you can try with the nightly containers:

https://hub.docker.com/r/rapidsai/rapidsai-nightly

**Comment by deltadu** [comment]
I tried the above code in nightly docker, but still received the same Error


Moreover, I tried a different way to create cudf.DataFrame and received a different Error. The reason for the error below seems to be that isintance(cudf.dataframe.series.Series, DeviceNDArray) returns False
```
>>> x = cudf.DataFrame({'a': range(10), 'b': range(10)})
>>> x.iloc[cudf.Series([0, 1, 2])]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 2900, in __getitem__
    df.index = self._df.index[arg]
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/index.py", line 357, in __getitem__
    raise ValueError(index)
ValueError: 0    0
1    1
2    2
dtype: int64
```

**Comment by kkraus14** [comment]
Looks like the error is in gathering the index, likely that the codepath in `index` doesn't handle a Series.

**Comment by thomcom** [comment]
Looks like it is working as of today.

**Comment by kkraus14** [comment]
Great, @deltadu could you try with the latest nightlies if possible?

**Comment by deltadu** [comment]
I pulled the nightly docker image, but still experiencing the problem, below is how I did it (please let me know if I missed something):
```
jianlind@dgx19:~$ docker pull rapidsai/rapidsai-nightly
Using default tag: latest
latest: Pulling from rapidsai/rapidsai-nightly
9ff7e2e5f967: Already exists
59856638ac9f: Already exists
6f317d6d954b: Already exists
a9dde5e2a643: Already exists
938828b684f3: Already exists
8c714894b788: Already exists
388ed6e4a282: Already exists
e4f4d37314cb: Already exists
65944a64ad0b: Already exists
9d0f7ec21fa5: Pull complete
Digest: sha256:45b45efd68e5ec201586a91472c7b4fce5be08d578d2fef6288c9e4ab2ec81a9
Status: Downloaded newer image for rapidsai/rapidsai-nightly:latest

jianlind@dgx19:~$ nvidia-docker run -it -d rapidsai/rapidsai-nightly
6872d676737448c5ba07c486d2c7a1ef1a842c89977d8a74452699d6e6a8300a

jianlind@dgx19:~$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                     NAMES
6872d6767374        rapidsai/rapidsai-nightly   "/usr/bin/tini -- /b…"   48 seconds ago      Up 46 seconds       8786-8787/tcp, 8888/tcp   stupefied_bell
269354c481d4        620207931eca                "/bin/bash -c 'if [ …"   2 minutes ago       Up 2 minutes                                  trusting_brown
0e7ae9408e2b        rapidsai/rapidsai:latest    "/usr/bin/tini -- /b…"   7 days ago          Up 19 hours         8786-8787/tcp, 8888/tcp   amazing_austin

jianlind@dgx19:~$ nvidia-docker exec -ti stupefied_bell /bin/bash
(rapids) root@6872d6767374:/rapids/notebooks# python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>> df = cudf.DataFrame([('a', list(range(20))),
... ('b', list(reversed(range(20)))),
... ('c', list(range(20)))])
>>> df.iloc[cudf.Series([0,1,2])]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 2900, in __getitem__
    df.index = self._df.index[arg]
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/index.py", line 357, in __getitem__
    raise ValueError(index)
ValueError: 0    0
1    1
2    2
dtype: int64
```



One the other hand, while I pulled rapidsai-nightly, a subsidiary docker image pataylor/rapidsai/cudf was pulled and **I am able to do cudf.Series indexing in that docker** after 'source activate cudf'

**Comment by kkraus14** [comment]
I'm digging in on . this, thanks for the reproducer!

**Comment by kkraus14** [comment]
@deltadu I'm unable to reproduce this on a fresh build from source using the exact code you put above so I believe it's resolved. It looks like the nightly containers haven't been built in a few days, but when they build this issue should be resolved.

**Comment by deltadu** [comment]
@kkraus14 
Ok, I got it. Thank you very much for trying to reproduce the failure!
Is it possible for you to also pull a nightly docker from dockerhub and try the code on it, since it worked well on Nick's machine with an image that he built from source, but failed on my machine with an image pulled from docker hub.
If it works well on a pulled nightly image on your machine, it is probably something wrong on my side

**Comment by kkraus14** [comment]
Closing this as it's working in conda + source, please reopen if it doesn't work in a new container once it's published.

**Comment by deltadu** [comment]
I finally found the issue: the rapidsai/rapidsai-nightly images still includes v0.7 of cudf, although the image tag is 0.8. Rick said the problem will be solved soon.

I pulled a internal image, everything works now
